apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  
spec: #we specify the way that the service behaves.
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
    targetPort: 5000